#!/usr/bin/env bash
set -xe

# install lix
# curl -sSf -L https://install.lix.systems/lix | sh -s -- install

# install homebrew
# /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

sudo nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
sudo nix-channel --add https://github.com/lnl7/nix-darwin/archive/master.tar.gz darwin
sudo nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
sudo nix-channel --update

nix-build '<darwin>' -A darwin-rebuild
NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1 ./result/bin/darwin-rebuild switch -I darwin-config=/Users/jojo/.dotfiles/nix/darwin-configuration.nix
# rm -rf ./result/
# ./nix-maint
